model:      "configs/modules/models/logistic_regression.yaml"
dataset:    "configs/datasets/heart_disease.yaml"
preprocess: "configs/modules/process/preprocess.yaml"
logs:       "configs/logs/core.yaml"