path: "datasets/raw/heart_disease.csv"

split:
  train_size:   0.9
  val_size:     0.1
  random_state: 38
  shuffle:      True

features:
  categorical:
    - "sex"       #sex                                    (1 = male; 0 = female)
    - "cp"        #chest pain type                        [0, 1, 2, 3]
    - "fbs"       #fasting blood sugar                    (>120 mg/dl (1 = true; 0 = false))
    - "restecg"   #resting electrocardiographic results   [0, 1, 2]
    - "exang"     #exercise induced angina                (1 = true; 0 = false)
    - "slope"     #slope of the peak exercise ST segment  [0, 1, 2]
    - "ca"        #number of major vessels                [0, 1, 2, 3, 4]
    - "thal"      #defects from normal to reversable      [0, 1, 2, 3]

  numerical:
    - "age"       #age in years
    - "trestbps"  #resting blood pressure(mm/hg)
    - "chol"      #serum cholestoral(mg/dl)
    - "thalach"   #maximum heart rate achieved
    - "oldpeak"   #ST depression induced by exercise relative to rest

  target:
    - "target"    #presence of heart disease in a patient (1 = true; 0 = false)