categorical:

  - name: "sex"
    min_value: 0
    max_value: 1

  - name: "cp"
    min_value: 0
    max_value: 3

  - name: "fbs"
    min_value: 0
    max_value: 1

  - name: "restecg"
    min_value: 0
    max_value: 2

  - name: "exang"
    min_value: 0
    max_value: 1

  - name: "slope"
    min_value: 0
    max_value: 2

  - name: "ca"
    min_value: 0
    max_value: 4

  - name: "thal"
    min_value: 0
    max_value: 3

numerical:

  - name: "age"
    min_value: 0
    max_value: 100

  - name: "trestbps"
    min_value: 0
    max_value: 400

  - name: "chol"
    min_value: 0
    max_value: 400

  - name: "thalach"
    min_value: 0
    max_value: 400

  - name: "oldpeak"
    min_value: 0.0
    max_value: 400

target:
  - name: "target"
    min_value: 0
    max_value: 1
