apiVersion: v1
kind: Pod
metadata:
  name: online-inference-probes
  labels:
    app: online-inference
spec:
  containers:
    - image: ilyabasharov/made_mail.ru:v3
      name: online-inference
      ports:
        - containerPort: 8000
      readinessProbe:
        httpGet:
          path: /
          port: 8000
        initialDelaySeconds: 15
        periodSeconds: 15
        failureThreshold: 10
      livenessProbe:
        httpGet:
          path: /
          port: 8000
        initialDelaySeconds: 60
        periodSeconds: 15
        failureThreshold: 10