name:            "SGDClassifier"
import_from:     "sklearn.linear_model"
path:            "modules/models/sgd_classifier.joblib"
kwargs:
  loss:          "modified_huber"
  penalty:       "l2"
  alpha:         0.001
  tol:           0.000001
  random_state:  38
  n_jobs:        -1
  eta0:          0.01
  learning_rate: "adaptive"